import { AuthenticatedTemplate, UnauthenticatedTemplate, useMsal } from '@azure/msal-react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

function SignInButton() {
  const { instance } = useMsal()
  return <button onClick={() => {instance.loginRedirect()}}>Sign In</button>
}

function WelcomeUser() {
  const { accounts } = useMsal()
  const username = accounts[0].username

  return <p>Welcome, {username}</p>
}

function SignOutButton() {
  const { instance } = useMsal()

  return <button onClick={() => instance.logoutRedirect()}>Sign Out</button>
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Azure Ad Auth with MSAL and NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthenticatedTemplate>
        <p>Esta página está restrita a usuários autenticados</p>
        <WelcomeUser/>
        <SignOutButton/>
      </AuthenticatedTemplate>
      <UnauthenticatedTemplate>
        <p>Você não está logado!</p>
        <SignInButton/>
      </UnauthenticatedTemplate>
    </div>
  )
}
